# Generated by Django 5.0.6 on 2026-05-18 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_title', models.CharField(max_length=100)),
                ('service_detail', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('business_email', models.EmailField(max_length=254)),
                ('location_url', models.URLField(max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city'], name='business_li_city_2dff14_idx'), models.Index(fields=['region'], name='business_li_region_f1a7e1_idx'), models.Index(fields=['is_active'], name='business_li_is_acti_e8cbdd_idx')],
            },
        ),
    ]
