# Generated by Django 5.0.6 on 2026-05-19 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesslisting",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesslisting",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="businesslisting",
            name="service_detail",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(2000)]
            ),
        ),
        migrations.AddIndex(
            model_name="businesslisting",
            index=models.Index(
                fields=["latitude", "longitude"], name="business_li_lat_lon_idx"
            ),
        ),
    ]
