# Generated by Django 5.0.6 on 2026-05-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_businesslisting_geo_and_service_detail_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='location_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
